

CREATE TABLE FICT.Legal_Entity_Type_Name_Types (
  LEGAL_ENTITY_TYPE_NAMES_TYPE_ID TINYINT UNSIGNED NOT NULL,
  LEGAL_ENTITY_TYPE_ID   TINYINT UNSIGNED NOT NULL,
  NAME_TYPE_ID    TINYINT UNSIGNED NOT NULL,

  PRIMARY KEY (`LEGAL_ENTITY_TYPE_NAMES_TYPE_ID`)
);

ALTER TABLE FICT.Legal_Entity_Type_Name_Types ADD CONSTRAINT Uq_On_Legal_Entity_Type_Name_Types
UNIQUE (LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID);


INSERT INTO FICT.Name_Type (NAME_TYPE_ID, NAME_TYPE_TEXT) VALUES (6, 'Agency');

INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (1, 1, 1);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (2, 1, 3);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (3, 1, 2);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (4, 1, 4);

INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (5, 2, 5);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (6, 3, 5);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (7, 4, 5);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (8, 5, 5);
INSERT INTO FICT.Legal_Entity_Type_Name_Types(LEGAL_ENTITY_TYPE_NAMES_TYPE_ID, LEGAL_ENTITY_TYPE_ID, NAME_TYPE_ID) VALUES (9, 6, 6);




INSERT INTO FICT.Address (ADDRESS_ID, STREET, CITY, STATE, ZIP_CODE) VALUES (1, '1934 11th Street', 'Santa Monica', 'CA', '90401');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('650 S.Hill Street', 'Los Angeles', 'CA', '90014');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('2001 Santa Monica Blvd', 'Santa Monica', 'CA', '90402');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('17030 Nordoff St', 'Northridge', 'CA', '91325');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('11963 Walnut Ln.', 'Santa Monica', 'CA', '90025');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('22000 Dumetz Road', 'Woodland Hills', 'CA', '91364');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('4041 N. Central Ave.', 'Phoenix', 'AZ', '85012');


INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('686 Ryan Court ', 'Beachwood', 'OH', '44122');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('926 Birchpond St.', 'Piscataway', 'NJ', '08854');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('969 Linda Rd. ', 'Ontario', 'CA', '91762');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('9769 Main Court ', 'Westwood', 'NJ', '07675');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('392 Old Augusta Lane', 'East Brunswick', 'NJ', '08816');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('631 Cedarwood Dr', 'Birmingham', 'AL', '35209');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('78 Penn Drive ', 'Wasilla', 'AK', '99654');

INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('720 East Randall Mill St.', 'Fredericksburg', 'VA', '22405');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('28 Jockey Hollow Avenue', 'Pelham', 'AL', '35124');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('8501 Lawrence Dr.', 'Jamaica Plain', 'MA', '02130');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('77 E. Division Drive', 'Crawfordsville', 'IN', '47933');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('7 Harvey Rd.', 'Glen Allen', 'VA', '23059');

INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('773 North Gulf St.', 'Oshkosh', 'WI', '54901');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('831 Ocean St. ', 'Sewell', 'NJ', '08080');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('854 Summerhouse St.', 'Panama City', 'FL', '32404');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('8891 S. Manhattan St. ', 'Hudson', 'NH', '03051');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('996 Indian Spring Ave.', 'Westland', 'MI', '48185');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('7 Windfall St. ', 'Buffalo', 'NY', '14215');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('665 Lantern Ave.', 'Elmhurst', 'NY', '11373');


INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('34 Arcadia Lane', 'Williamsburg', 'VA', '23185');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('8038 Newport St.', 'Wayne', 'NJ', '07470');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('8821 Old Manor Station St.', 'Woodbridge', 'VA', '22191');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('790 Johnson Street.', 'Champaign', 'IL', '61821');
INSERT INTO FICT.Address (STREET, CITY, STATE, ZIP_CODE) VALUES ('8038 Newport St. ', 'Cape Coral', 'FL', '33904');


INSERT INTO FICT.Entity_Address (ENTITY_ADDRESS_ID, LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(1, 1, 1, 1);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(1, 3, 2);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(1, 2, 3);

INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(5, 7, 4);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(5, 7, 5);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(5, 7, 6);

INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(9, 2, 7);

INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(3, 1, 1);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(3, 3, 9);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(3, 2, 10);

INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(5, 7, 11);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(5, 7, 12);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(5, 7, 13);

INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(6, 7, 14);


INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 15);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 16);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 17);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 18);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 19);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 20);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 21);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 22);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 23);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 24);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 25);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 26);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 27);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 28);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 29);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(10, 4, 30);


INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(11, 5, 31);
--INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(11, 4, 32);
/*
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(12, 5, 33);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(13, 5, 34);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(14, 5, 35);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(15, 5, 36);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(15, 5, 37);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(16, 5, 38);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(17, 5, 39);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(18, 5, 40);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(19, 5, 41);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(20, 5, 42);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(21, 5, 43);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(22, 5, 44);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(23, 5, 45);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(23, 4, 46);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(23, 4, 47);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(23, 4, 48);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(23, 4, 49);
INSERT INTO FICT.Entity_Address (LEGAL_ENTITY_ID, ADDRESS_TYPE_ID, ADDRESS_ID) VALUES(23, 4, 50);*/
