package com.murun.fict.repository;


import com.murun.fict.main.ApplicationConfig;
import com.murun.fict.model.EntityAddress;
import com.murun.fict.model.EntityName;
import com.murun.fict.model.LegalEntity;
import com.murun.fict.model.LegalEntityType;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;

import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

//@ActiveProfiles("properties.dev")
@RunWith(SpringRunner.class)
//@SpringBootTest
@ContextConfiguration(classes= ApplicationConfig.class)
//@DataJpaTest
public class LegalEntityRepositoryTest {



    @Resource
    LegalEntityRepository legalEntityRepository;


    @Test
    public void shouldSaveWithAutoGeneratedId() {


        LegalEntityType legalEntityType = new LegalEntityType();
        Set<EntityName> entityNames = new HashSet<>();
        Set<EntityAddress> entityAddress = new HashSet<>();
        LegalEntity legalEntity = new LegalEntity(legalEntityType, entityNames, entityAddress);


        assertNull(legalEntity.getLegalEntityId());
        legalEntityRepository.save(legalEntity);
        assertNotNull(legalEntity.getLegalEntityId());
        assertEquals( 1, legalEntity.getLegalEntityId().intValue());
    }

}
